### PR TITLE
Bug fixes for Safari

### PR DESCRIPTION
**Pull request by santhisenan**
Fixed a small bug in Safari in which the henosis will move to top left corner of the window when it is dragged.

### CODE REVIEW

**Comment by jilvin** [comment]
Unstable containment in Chromium browser.

**Comment by santhisenan** [comment]
Solved the containment issue in chrome/chromium and safari.

**Comment by jilvin** [comment]
@santhisenan  Actually the containment is provided by jquery UI library and is used here. The changes you made is really appreciated and is great. But if possible stick to previous jquery UI containment as to make the code more elegant. :)

**Comment by jilvin** [comment]
@santhisenan Can you kindly check if the current code is working on both MacOS and iOS without errors?

**Comment by santhisenan** [comment]
@jilvin Yes, it is working properly in Safari on both iOS and MacOS.

**Pull request merged**
